package=com.banking.transactionlog
systemProp.version=4.7.0
reactive=false
lombok=true
metrics=true
language=java
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.integrity-check=false
org.gradle.configuration-cache.read-only=false
systemProp.sonar.gradle.skipCompile=true
